---
config:
  layout: elk
---
flowchart TD
    IA["🤖 Inteligencia Artificial"] --> ML["📘 Machine Learning"]
    ML --> DL["🔬 Deep Learning"]
    DS["📊 Ciencia de Datos"] --> ML & DM["⛏️ Minería de Datos"] & EST["📐 Estadística"] & BD["📌 Big Data"]
    DM --> EST & BD
    BI["📈 Inteligencia de Negocios"] --> DS & BD
